---
title: "git_01"
author: "Math_116"
date: "Spring Semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves   
      Did gyre and gimble in the wabe:   
All mimsy were the borogoves,   
      And the mome raths outgrabe.   

“Beware the Jabberwock, my son!   

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Something there is that doesn't love a wall,  
That sends the frozen-ground-swell under it,  
And spills the upper boulders in the sun;  
And makes gaps even two can pass abreast.  
The work of hunters is another thing:  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Take this kiss upon the brow!  
And, in parting from you now, 
Thus much let me avow —  
You are not wrong, who deem  
That my days have been a dream;  
Yet if hope has flown away  
In a night, or in a day,  
In a vision, or in none,  
Is it therefore the less gone?    
All that we see or seem  
Is but a dream within a dream.  
